# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20170925_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='doing',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
        migrations.AddField(
            model_name='done',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
        migrations.AddField(
            model_name='test',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
        migrations.AddField(
            model_name='todo',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        ),
        migrations.AlterField(
            model_name='doing',
            name='doing_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='done',
            name='done_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_text',
            field=models.TextField(null=True),
        ),
    ]
