# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20170926_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doing',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.UserList'),
        ),
        migrations.AlterField(
            model_name='done',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.UserList'),
        ),
        migrations.AlterField(
            model_name='test',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.UserList'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.UserList'),
        ),
    ]
