# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20170926_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='UserList',
            new_name='Board',
        ),
        migrations.RemoveField(
            model_name='doing',
            name='user_list',
        ),
        migrations.RemoveField(
            model_name='done',
            name='user_list',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user_list',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user_list',
        ),
        migrations.DeleteModel(
            name='Doing',
        ),
        migrations.DeleteModel(
            name='Done',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='row',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Board'),
        ),
        migrations.AddField(
            model_name='item',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Row'),
        ),
    ]
