# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20170926_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='first_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='back',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='front',
            field=models.IntegerField(default=0),
        ),
    ]
