# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20170927_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
