# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20171009_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='first_row',
            new_name='first_element',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='first_item',
            new_name='first_element',
        ),
    ]
