# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20171016_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='name',
        ),
    ]
